Revert "Reland^3 "build: Enable clang modules on Windows""
This reverts commit 0628149457f2c5ccb5a7e4c62e1ecf8a8f417713.

Reason for revert: Suspect for breaking win64-chrome
../..\chrome/browser/platform_experience/win/localization.h(13,33): error: declaration of 'uint16_t' must be imported from module '//build/modules:system.stdint.h' before it is required
   13 | std::wstring GetLocalizedString(uint16_t message_id);

Failure Link: https://ci.chromium.org/ui/p/chrome/builders/ci/win64-chrome/33886/overview

Original change's description:
> Reland^3 "build: Enable clang modules on Windows"
>
> This reverts commit c359cc6c63b6e308bb7025e426489c41bbfed9d6.
>
> Reason for revert: Fix for previous error was landed as
> https://crrev.com/c/8253300
>
> Original change's description:
> > [Gardening] Revert "Reland "Reland "build: Enable clang modules on Windows"""
> >
> > This reverts commit f0cddcf7f71ede499bac026c144e7d1c9713ee03.
> >
> > Reason for revert: Causing windows build issues
> >
> > Failure Link: Example, https://ci.chromium.org/ui/p/chrome/builders/ci/win64-rel-ready/96357/overview
> >
> > Original change's description:
> > > Reland "Reland "build: Enable clang modules on Windows""
> > >
> > > This reverts commit 5f0c14504ee582bad4de0211f5a2147898d57d6a.
> > >
> > > Reason for revert: Falsy revert as this CL shouldn't affect ChromeOS
> > > build.
> > >
> > > Original change's description:
> > > > Revert "Reland "build: Enable clang modules on Windows""
> > > >
> > > > This reverts commit 5b0d678a4469fc7729507f4cda4072edb51ea59e.
> > > >
> > > > Reason for revert:
> > > > LUCI Bisection has identified this change as the culprit of a build failure. See the analysis: https://ci.chromium.org/ui/p/chromium/bisection/compile-analysis/b/8673611306322760673
> > > >
> > > > Sample failed build: https://ci.chromium.org/b/8673611306322760673
> > > >
> > > > If this is a false positive, please report it at http://b.corp.google.com/createIssue?component=1199205&description=Analysis%3A+https%3A%2F%2Fchromium-review.googlesource.com%2Fc%2Fchromium%2Fsrc%2F%2B%2F8247421&format=PLAIN&priority=P3&title=Wrongly+blamed+https%3A%2F%2Fci.chromium.org%2Fui%2Fp%2Fchromium%2Fbisection%2Fcompile-analysis%2Fb%2F8673611306322760673&type=BUG
> > > >
> > > > Original change's description:
> > > > > Reland "build: Enable clang modules on Windows"
> > > > >
> > > > > This reverts commit 9cffbe44a37cb9a532f25f2fe20c7f586aa700dd.
> > > > >
> > > > > Reason for revert: Don't enable clang modules for x86 build this time.
> > > > >
> > > > > Original change's description:
> > > > > > Revert "build: Enable clang modules on Windows"
> > > > > >
> > > > > > This reverts commit 42983d3db9d3478e41cc4491535f7f3a8db83bba.
> > > > > >
> > > > > > Reason for revert:
> > > > > > Build failure on Windows and this is identified as the culprit by the system.
> > > > > >
> > > > > > Failure Link:
> > > > > > https://ci.chromium.org/ui/p/chromium/builders/ci/Win%20Builder/283574/overview
> > > > > >
> > > > > > Original change's description:
> > > > > > > build: Enable clang modules on Windows
> > > > > > >
> > > > > > > We submitted https://crrev.com/c/8204706 as a workaround for the
> > > > > > > previous build failure.
> > > > > > >
> > > > > > > Bug: 425537956
> > > > > > > Cq-Include-Trybots: luci.chromium.try:win32-clobber-rel
> > > > > > > Change-Id: I2833eef86f2fe44a82f8d5c6db12a68bc1aa3788
> > > > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8223469
> > > > > > > Reviewed-by: Junji Watanabe <jwata@google.com>
> > > > > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > > > > > Reviewed-by: Matt Stark <msta@google.com>
> > > > > > > Cr-Commit-Position: refs/heads/main@{#1677800}
> > > > > >
> > > > > > Bug: 425537956
> > > > > > Cq-Include-Trybots: luci.chromium.try:win32-clobber-rel
> > > > > > No-Presubmit: true
> > > > > > No-Tree-Checks: true
> > > > > > No-Try: true
> > > > > > Change-Id: I9cf0f2229505218717c78f30405f2b61ab5f26a1
> > > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8246461
> > > > > > Owners-Override: Huanpo Lin <robertlin@chromium.org>
> > > > > > Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> > > > > > Auto-Submit: Huanpo Lin <robertlin@chromium.org>
> > > > > > Commit-Queue: Huanpo Lin <robertlin@chromium.org>
> > > > > > Cr-Commit-Position: refs/heads/main@{#1677810}
> > > > >
> > > > > Bug: 425537956
> > > > > Cq-Include-Trybots: luci.chromium.try:win32-clobber-rel
> > > > > Change-Id: I0fb91a971ee35805ee38ef8adb03599b3f0ef806
> > > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8247421
> > > > > Reviewed-by: Junji Watanabe <jwata@google.com>
> > > > > Reviewed-by: Matt Stark <msta@google.com>
> > > > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > > > Cr-Commit-Position: refs/heads/main@{#1678592}
> > > > >
> > > >
> > > > Bug: 425537956
> > > > No-Presubmit: true
> > > > No-Tree-Checks: true
> > > > No-Try: true
> > > > Change-Id: I6f3d1e9b59869303f9599584d77742fef714caa6
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8252624
> > > > Bot-Commit: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> > > > Commit-Queue: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> > > > Owners-Override: luci-bisection@appspot.gserviceaccount.com <luci-bisection@appspot.gserviceaccount.com>
> > > > Cr-Commit-Position: refs/heads/main@{#1678613}
> > >
> > > Bug: 425537956
> > > Cq-Include-Trybots: luci.chromium.try:chromeos-amd64-generic-dbg
> > > Change-Id: I5b1a8a2c5d494579323d91fbf5a1edfeafd695a9
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8255289
> > > Reviewed-by: Matt Stark <msta@google.com>
> > > Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> > > Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> > > Cr-Commit-Position: refs/heads/main@{#1678671}
> >
> > Bug: 425537956
> > Cq-Include-Trybots: luci.chromium.try:chromeos-amd64-generic-dbg
> > Change-Id: I4757e80a0481ab20de714e9bd78b7e5994fb380f
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8256293
> > Commit-Queue: Ian Vollick <vollick@chromium.org>
> > Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> > Reviewed-by: Junji Watanabe <jwata@google.com>
> > Reviewed-by: Nicola Tommasi <tommasin@chromium.org>
> > Owners-Override: Nicola Tommasi <tommasin@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1678906}
>
> Bug: 425537956
> Cq-Include-Trybots: luci.chromium.try:chromeos-amd64-generic-dbg
> Cq-Include-Trybots: luci.chrome.try:win64-rel-ready
> Change-Id: I5d65a16bc5b38e6ed297f0174ee57a6245b59665
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8255210
> Reviewed-by: Matt Stark <msta@google.com>
> Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1679343}

Bug: 425537956
Cq-Include-Trybots: luci.chromium.try:chromeos-amd64-generic-dbg
Cq-Include-Trybots: luci.chrome.try:win64-rel-ready
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I48987ca99c8affd881188b44ecdb4e0ed1bcda0e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8257881
Commit-Queue: Kevin McNee <mcnee@chromium.org>
Auto-Submit: Kevin McNee <mcnee@chromium.org>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Kevin McNee <mcnee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1679571}
NOKEYCHECK=True
GitOrigin-RevId: 71ab77a0020451344cad3fd3dcd82d88f9fef572