Reland #2: "private_code_test: Parse build.ninja to collect linker inputs"
This reverts commit f58220e29690ead1beb940a8824096b8071c7489.

Reason for reland: Disabled test for is_component_build=true

Also removed the now unnecessary --collect-inputs-only copy of
chrome executable.

Original change's description:
> Revert "Reland "private_code_test: Parse build.ninja to collect linker inputs""
>
> This reverts commit 269acc3c8ad1b3aad5dd807f6fa99db30c3a4e10.
>
> Reason for revert: Failing locally:
>     logging.info('Found %d linker inputs', len(object_paths))
>                                            ^^^^^^^^^^^^^^^^^
> TypeError: object of type 'NoneType' has no len()
> build failed
>
>
> Original change's description:
> > Reland "private_code_test: Parse build.ninja to collect linker inputs"
> >
> > This reverts commit 83e7953b9679c76170adf1b02e13e129e3c6de75.
> >
> > Reason for revert: Adds non-deterministics files to ignorelist
> >
> > Original change's description:
> > > Revert "private_code_test: Parse build.ninja to collect linker inputs"
> > >
> > > This reverts commit a6dddc3de16b5c67656254e10ed648354cd3a4f0.
> > >
> > > Reason for revert: Suspected of causing failure in deterministic build - https://ci.chromium.org/ui/p/chromium/builders/ci/Deterministic%20Linux/51954 (https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8725202020735429233/+/u/compare_build_artifacts/stdout)
> > >
> > > Original change's description:
> > > > private_code_test: Parse build.ninja to collect linker inputs
> > > >
> > > > Although slower, this handles the case where GN targets are in public
> > > > code, but include source files from private code.
> > > >
> > > > Bug: 40204298
> > > > Change-Id: If571518f07855946a16e5aeebe0cace661cc75dd
> > > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5756917
> > > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > > > Cr-Commit-Position: refs/heads/main@{#1408713}
> > >
> > > Bug: 40204298
> > > Change-Id: I9584a8e46d28ce0f64d263c88d8041cb51368471
> > > No-Presubmit: true
> > > No-Tree-Checks: true
> > > No-Try: true
> > > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6184083
> > > Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> > > Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> > > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > > Cr-Commit-Position: refs/heads/main@{#1408751}
> >
> > Bug: 40204298
> > Change-Id: I330e111f9cf3ca47af8d5c5142d362728a1c429a
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6185547
> > Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> > Reviewed-by: Dirk Pranke <dpranke@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1409216}
>
> Bug: 40204298
> Change-Id: Ia4f3026884ed49606ac337de5f441ade433b9f0e
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6187366
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Owners-Override: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Auto-Submit: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1409266}

Bug: 40204298
Change-Id: If2c86c7acf2634520bfe89c0eca26d832ae939f0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6194532
Reviewed-by: Dirk Pranke <dpranke@google.com>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1410508}
NOKEYCHECK=True
GitOrigin-RevId: ad1ae9d3bc165c1fac50d2b54197e3569dd00fc5